version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:jfKKUcbgiCTjKSthhGVDGjLoE698zn4ZoiNcQAFQLHA=
      APP_DEBUG: "true"
      APP_TIMEZONE: UTC
      APP_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:3000
      DB_CONNECTION: pgsql
      DB_HOST: dpg-cpg117779t8c73ebge2g-a
      DB_PORT: 5432
      DB_DATABASE: sysqube
      DB_USERNAME: root
      DB_PASSWORD: E2A23jKIzcupNZJteAiVW6GUAc5E97dW
    volumes:
      - .:/var/www/html
    command: ["php-fpm"]
